/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ProcedimentosRouteImport } from './routes/procedimentos'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as PacientesIndexRouteImport } from './routes/pacientes/index'
import { Route as PacientesIdRouteImport } from './routes/pacientes/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcedimentosRoute = ProcedimentosRouteImport.update({
  id: '/procedimentos',
  path: '/procedimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesIndexRoute = PacientesIndexRouteImport.update({
  id: '/pacientes/',
  path: '/pacientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesIdRoute = PacientesIdRouteImport.update({
  id: '/pacientes/$id',
  path: '/pacientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/produtos': typeof ProdutosRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/estoque': typeof EstoqueRoute
  '/equipe': typeof EquipeRoute
  '/pacientes/': typeof PacientesIndexRoute
  '/pacientes/$id': typeof PacientesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/produtos': typeof ProdutosRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/estoque': typeof EstoqueRoute
  '/equipe': typeof EquipeRoute
  '/pacientes': typeof PacientesIndexRoute
  '/pacientes/$id': typeof PacientesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/produtos': typeof ProdutosRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/estoque': typeof EstoqueRoute
  '/equipe': typeof EquipeRoute
  '/pacientes/': typeof PacientesIndexRoute
  '/pacientes/$id': typeof PacientesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/produtos'
    | '/procedimentos'
    | '/estoque'
    | '/equipe'
    | '/pacientes/'
    | '/pacientes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/produtos'
    | '/procedimentos'
    | '/estoque'
    | '/equipe'
    | '/pacientes'
    | '/pacientes/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/produtos'
    | '/procedimentos'
    | '/estoque'
    | '/equipe'
    | '/pacientes/'
    | '/pacientes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProdutosRoute: typeof ProdutosRoute
  ProcedimentosRoute: typeof ProcedimentosRoute
  EstoqueRoute: typeof EstoqueRoute
  EquipeRoute: typeof EquipeRoute
  PacientesIndexRoute: typeof PacientesIndexRoute
  PacientesIdRoute: typeof PacientesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedimentos': {
      id: '/procedimentos'
      path: '/procedimentos'
      fullPath: '/procedimentos'
      preLoaderRoute: typeof ProcedimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes/': {
      id: '/pacientes/'
      path: '/pacientes/'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof PacientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes/$id': {
      id: '/pacientes/$id'
      path: '/pacientes/$id'
      fullPath: '/pacientes/$id'
      preLoaderRoute: typeof PacientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProdutosRoute: ProdutosRoute,
  ProcedimentosRoute: ProcedimentosRoute,
  EstoqueRoute: EstoqueRoute,
  EquipeRoute: EquipeRoute,
  PacientesIndexRoute: PacientesIndexRoute,
  PacientesIdRoute: PacientesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
